import {Screens} from '../enums';

export type RootParamList = {
  [Screens.PHONE]: undefined;
  [Screens.NAME]: undefined;
  [Screens.CODE]: undefined;
  [Screens.YOUR_GARAGE_LIST]: undefined;
  [Screens.LIST_CAR_ITEMS]: {listType: string; step?: number};
  [Screens.TABS]: undefined;
  [Screens.HOME]: undefined;
  [Screens.CATALOG]: undefined;
  [Screens.GARAGE_LIST]: undefined;
  [Screens.PROFILE]: undefined;
  [Screens.RATES]: undefined;
  [Screens.RATE_CONDITIONS]: {rate: any};
  [Screens.RATE_PAYMENT]: undefined;
  [Screens.SUPPORT]: undefined;
  [Screens.ADD_CAR]: undefined;
  [Screens.EDIT_CAR]: {carId: string};
  [Screens.SEARCH_CATALOG]: undefined;
  [Screens.FILTER]: undefined;
  [Screens.SERVICE]: undefined;
  [Screens.BRANDS_LIST]: undefined;
  [Screens.BRANDS_LIST_MAP]: undefined;
  [Screens.INVITE]: undefined;
  [Screens.REVIEW_BRAND]: {brandId: string};
  [Screens.GARAGE_CARD]: {carId: string};
  [Screens.BRAND_CARD]: {brandId: string};
  [Screens.GALLERY]: {images?: any};
  [Screens.CAR_CHARACTERISTICS]: {item: any};
  [Screens.SERVICE_HISTORY]: {item: any};
  [Screens.SERVICE_ENTRY]: {taskId: string};
  [Screens.SERVICE_EDIT_RECORD]: {item: any};
  [Screens.ANALYTICS]: undefined;
  [Screens.LOADING]: undefined;
  [Screens.ANALYTICS_PERIOD]: undefined;
  [Screens.NOTIFICATION_GARAGE]: {carItem: any};
  [Screens.CONTACT_SETTINGS]: {contactId: string};
  [Screens.ADD_DRIVER]: {carId: string; sharedWith: any};
  [Screens.CALENDAR]: undefined;
  [Screens.EDIT_PROFILE]: {item: any};
  [Screens.PROFILE_CODE]: undefined;
  [Screens.PROFILE_PHONE]: undefined;
  [Screens.PROFILE_CODE_VERIFICATION]: undefined;
  [Screens.PROFILE_FAVORITE]: undefined;
  [Screens.CONTACT_LIST]: undefined;
  [Screens.MY_REVIEWS]: undefined;
  [Screens.NOTIFICATION_LIST]: undefined;
  [Screens.NOTIFICATION_INVITE_ID]: {notificationId: string};
  [Screens.NOTIFICATION_REVIEW_ID]: undefined;
  [Screens.NOTIFICATION_SERVICE_ID]: undefined;
  [Screens.NOTIFICATION_SUBSCRIPTE_ID]: undefined;
  [Screens.CONTACT_ADD]: undefined;
  [Screens.BLACK_LIST]: undefined;
  [Screens.SERVICE_ADD_RECORD]: {carId: string};
  [Screens.LIFEHACKS_LIST]: undefined;
  [Screens.LIFEHACKS_CARD]: {lifehackId: string};
  [Screens.EDIT_MY_REVIEW]: {item: string};
  [Screens.PROMO_CODE]: {brandIdItem: any};
  [Screens.NOTIFICATION_SETTINGS]: undefined;
  [Screens.REPORT]: {
    legalName?: string;
    address?: string;
    image: string;
    brandId: string;
  };
  [Screens.PHONE_CONTACTS_LIST]: undefined;
};
